# Generated by Django 3.2.6 on 2021-08-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', models.CharField(max_length=11, verbose_name='HP Number')),
                ('vehicle_year_make', models.CharField(max_length=4)),
                ('vehicle_model', models.CharField(max_length=128)),
                ('vehicle_no', models.CharField(max_length=10)),
                ('date_accident', models.DateField(verbose_name='Date of Accident')),
                ('time_accident', models.TimeField(help_text='<br/>HH:MM am/pm', verbose_name='Time of Accident')),
                ('location', models.CharField(max_length=128, verbose_name='Location of Accident')),
                ('type_loss', models.CharField(choices=[('OD', 'Own Damage'), ('KfK', 'Knock for Knock'), ('WD', 'Windscreen Damage'), ('Th', 'Theft')], default='OD', max_length=3, verbose_name='Accident Type')),
                ('desc_of_loss', models.TextField(verbose_name='Description')),
                ('is_report_lodged', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1, verbose_name='Are any reports lodged?')),
                ('is_any_injured', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1, verbose_name='Is anyone injured in the accident?')),
                ('claim_status', models.CharField(choices=[('IP', 'In Progress'), ('AC', 'Accepted')], default='IP', max_length=2)),
            ],
        ),
    ]
