# Generated by Django 3.2.6 on 2021-08-23 06:31

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claims',
            name='pdf_insurance_cover',
            field=models.FileField(default=django.utils.timezone.now, help_text='Supported Formats: pdf', upload_to='pdf', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Insurance Cover'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claims',
            name='photo',
            field=models.ImageField(default=1, upload_to='img', verbose_name='Images of Accident'),
            preserve_default=False,
        ),
    ]
