# Generated by Django 3.2.6 on 2021-08-28 07:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0006_alter_claims_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='claim_status',
            field=models.CharField(choices=[('IP', 'In Progress'), (
                'AC', 'Accepted')], default='IP', max_length=2, verbose_name='Claim Status'),
        ),
        migrations.AlterField(
            model_name='claims',
            name='desc_of_loss',
            field=models.TextField(verbose_name='Description of Accident'),
        ),
        migrations.AlterField(
            model_name='claims',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='claims',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='claims',
            name='vehicle_model',
            field=models.CharField(
                max_length=128, verbose_name='Vehicle Name'),
        ),
        migrations.AlterField(
            model_name='claims',
            name='vehicle_no',
            field=models.CharField(
                max_length=10, verbose_name='Vehicle Plate Number'),
        ),
        migrations.AlterField(
            model_name='claims',
            name='vehicle_year_make',
            field=models.PositiveSmallIntegerField(default=2021, validators=[django.core.validators.MaxValueValidator(
                2021), django.core.validators.MinValueValidator(1950)], verbose_name='Vehicle Year Make'),
        ),
    ]
